INFO - 2023-12-13 10:37:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 10:37:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 10:37:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 10:37:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 10:37:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 10:37:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-12-13 10:38:08 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'mysql', 'psb_online_ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-12-13 10:38:08 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_user`
WHERE `email` = :email:
AND `password` = :password:', [...], false)
 3 APPPATH\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\SKRIPSI_PSB_ONLINE\\public\\index.php')
INFO - 2023-12-13 10:38:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 10:58:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 10:58:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-12-13 10:58:30 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'mysql', 'psb_online_ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-12-13 10:58:30 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_user`
WHERE `email` = :email:
AND `password` = :password:', [...], false)
 3 APPPATH\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\SKRIPSI_PSB_ONLINE\\public\\index.php')
INFO - 2023-12-13 10:58:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-12-13 10:58:46 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'mysql', 'psb_online_ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-12-13 10:58:46 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_user`
WHERE `email` = :email:
AND `password` = :password:', [...], false)
 3 APPPATH\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\SKRIPSI_PSB_ONLINE\\public\\index.php')
INFO - 2023-12-13 10:59:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 10:59:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-12-13 11:04:36 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'mysql', 'psb_online_ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-12-13 11:04:36 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_user`
WHERE `email` = :email:
AND `password` = :password:', [...], false)
 3 APPPATH\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\SKRIPSI_PSB_ONLINE\\public\\index.php')
INFO - 2023-12-13 11:05:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-12-13 11:05:41 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'mysql', 'psb_online_ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-12-13 11:05:41 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_user`
WHERE `email` = :email:
AND `password` = :password:', [...], false)
 3 APPPATH\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\SKRIPSI_PSB_ONLINE\\public\\index.php')
ERROR - 2023-12-13 11:06:01 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'mysql', 'psb_online_ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-12-13 11:06:01 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_user`
WHERE `email` = :email:
AND `password` = :password:', [...], false)
 3 APPPATH\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\SKRIPSI_PSB_ONLINE\\public\\index.php')
INFO - 2023-12-13 11:06:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-12-13 11:06:07 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'mysql', 'psb_online_ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-12-13 11:06:07 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_user`
WHERE `email` = :email:
AND `password` = :password:', [...], false)
 3 APPPATH\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\SKRIPSI_PSB_ONLINE\\public\\index.php')
ERROR - 2023-12-13 11:06:50 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'mysql', 'psb_online_ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-12-13 11:06:50 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_user`
WHERE `email` = :email:
AND `password` = :password:', [...], false)
 3 APPPATH\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\SKRIPSI_PSB_ONLINE\\public\\index.php')
ERROR - 2023-12-13 11:07:46 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'mysql', 'psb_online_ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-12-13 11:07:46 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_user`
WHERE `email` = :email:
AND `password` = :password:', [...], false)
 3 APPPATH\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\SKRIPSI_PSB_ONLINE\\public\\index.php')
ERROR - 2023-12-13 12:10:51 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'mysql', '', 3306, '', 0)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-12-13 12:10:51 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_user`
WHERE `email` = :email:
AND `password` = :password:', [...], false)
 3 APPPATH\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\SKRIPSI_PSB_ONLINE\\public\\index.php')
INFO - 2023-12-13 12:10:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-12-13 12:10:56 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'mysql', '', 3306, '', 0)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-12-13 12:10:56 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_user`
WHERE `email` = :email:
AND `password` = :password:', [...], false)
 3 APPPATH\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\SKRIPSI_PSB_ONLINE\\public\\index.php')
ERROR - 2023-12-13 12:11:31 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'mysql', 'psb_online_ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-12-13 12:11:31 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_user`
WHERE `email` = :email:
AND `password` = :password:', [...], false)
 3 APPPATH\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\SKRIPSI_PSB_ONLINE\\public\\index.php')
INFO - 2023-12-13 12:11:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-12-13 12:17:22 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'mysql', 'psb_online_ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-12-13 12:17:22 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_user`
WHERE `email` = :email:
AND `password` = :password:', [...], false)
 3 APPPATH\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '1234')
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\SKRIPSI_PSB_ONLINE\\public\\index.php')
INFO - 2023-12-13 12:17:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 12:19:09 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-12-13 12:21:07 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'mysql', 'psb_online_ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '@bSbiz7MrR4E9PJ')
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\app\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '@bSbiz7MrR4E9PJ')
#5 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
#6 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\SKRIPSI_PSB_ONLINE\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-12-13 12:21:07 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_user`
WHERE `email` = :email:
AND `password` = :password:', [...], false)
 3 APPPATH\Models\ModelAuth.php(16): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Auth.php(46): App\Models\ModelAuth->login_user('admin@gmail.com', '@bSbiz7MrR4E9PJ')
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Auth->cek_login_user()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\SKRIPSI_PSB_ONLINE\\public\\index.php')
INFO - 2023-12-13 12:28:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 12:28:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 12:28:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 12:28:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 12:28:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 12:28:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2023-12-13 12:28:41 --> Undefined variable: title
in APPPATH\Views\template\template-backend-admin.php on line 11.
 1 APPPATH\Views\template\template-backend-admin.php(11): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'C:\\xampp\\htdocs\\SKRIPSI_PSB_ONLINE\\app\\Views\\template\\template-backend-admin.php', 11, [])
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\SKRIPSI_PSB_ONLINE\\app\\Views\\template\\template-backend-admin.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\View\View.php(244): CodeIgniter\View\View->render('template/template-backend-admin', [], true)
 5 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('admin/v_dashboard', [], true)
 6 APPPATH\Controllers\Admin.php(11): view('admin/v_dashboard')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Admin->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\SKRIPSI_PSB_ONLINE\\public\\index.php')
INFO - 2023-12-13 12:30:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 12:31:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 12:31:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 12:31:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 12:31:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 12:31:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 12:31:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 12:31:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 12:31:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 12:31:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 12:31:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 12:32:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 12:32:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 12:32:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 12:32:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 12:32:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 22:55:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 22:55:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 22:55:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 22:55:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 22:55:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 22:55:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 22:55:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 22:55:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 22:55:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 22:55:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 22:55:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 22:55:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 22:55:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 22:56:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 22:56:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 22:56:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 22:56:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 22:56:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 22:56:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 22:56:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 22:56:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 22:56:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 22:56:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 22:56:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
